services:
  - type: web
    name: novel-reader-web
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.14.0
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
